### ISSUE TITLE
on use

### ISSUE THREAD

**Issue by Andyauk** [antond15/ac_radio#3]
i understand you can do /radio will you get it to work on use. keep up the great work.

**Comment by antond15** [comment]
To make a usable item, set `useCommand` to `false` and read the [item docs](https://github.com/antond15/ac_radio/tree/main/docs/items).

**Comment by Zzeyy** [comment]
@antond15 https://github.com/acscripts/ac_radio/tree/main/docs/items
Not really working

**Comment by antond15** [comment]
> Not really working

Well that's an issue from May 1st 2022, so some things changed.
Docs are now [here](https://docs.dejv.it/ac_radio).
