### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by jumalley** [antond15/ac_radio#6]
### Version

latest from github

### Issue description

![image](https://user-images.githubusercontent.com/50602425/169180888-2002c27c-1ab7-4a1c-92d2-73e03f76f18e.png)

I havent changed the locale and its not working on any languages i tried :/

### Steps to reproduce

1. Download newest version
2. Restart ressource
3. Restart server
4. Still broken :/

**Comment by antond15** [comment]
You didn't provide any useful information to reproduce the issue, so try it again. Every single step is useless for me, even the title is missing.

Bruh.
